In [1]:
import numpy as np

In [2]:
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])

Printing a range of Arrays

with the use of slicing method


In [3]:
arr2 = arr[::2, ::2]
print(arr2)

[[-1.   0. ]
 [ 2.6  7. ]]


Data types


Integer Datatype

In [4]:
arr = np.array([1,2])
print(arr.dtype)

int64


Float datatype


In [6]:
x = np.array([1.0, 2.0])
print(x.dtype)


float64


Forced Datatype

In [7]:
x = np.array([1,2], dtype = np.int64)
print(x.dtype)

int64


In [8]:
# first array
arr1 = np.array([[4,7], [2,6]], dtype=np.float64)

# Second array
arr2 = np.array([[3,6], [2,8]], dtype=np.float64)

array addition

In [10]:
Sum = np.add(arr1, arr2)
print(Sum)

[[ 7. 13.]
 [ 4. 14.]]


Addition of all array elements

In [11]:
Sum1 = np.sum(arr1)
print(Sum1)

19.0


Square root of Array

In [12]:
Sqrt = np.sqrt(arr1)
print(Sqrt)

[[2.         2.64575131]
 [1.41421356 2.44948974]]


Transpose of Array

In [13]:
Trans_arr = arr1.T
print(Trans_arr)

[[4. 2.]
 [7. 6.]]


hypot method

In [14]:
leg1 = [12, 3, 4, 6]
print("Leg1 array : ", leg1)

leg2 = [5, 4, 3, 8]
print("leg2 array : ", leg2 )

result = np.hypot(leg1, leg2)
print(result)

Leg1 array :  [12, 3, 4, 6]
leg2 array :  [5, 4, 3, 8]
[13.  5.  5. 10.]


Checking if the list is empty

using len

In [15]:
a = []
if len(a) == 0:
    print("The list is empty")
else:
    print("The list is not empty")

The list is empty


using not

In [17]:
a = [1]
if not a:
    print("empty list")
else:
    print("List is not empty")

List is not empty


Using boolean Evaluation Directly

In [20]:
a = [2]
if a:
    print("The list is not empty")
else:
    print("The list is empty")

The list is not empty


Get unique values from a list in python

using dict.fromkeys()

In [21]:
a = [1,2,1,1,3,4,3,3,5]
res = list(dict.fromkeys(a))
print(res)

[1, 2, 3, 4, 5]


Using SET conversion

In [2]:
a = [1, 2, 1, 1, 3, 4, 3, 3, 5]
res = list(set(a))
print(res)

[1, 2, 3, 4, 5]


Using FOR loops for getting unique value 

In [3]:
a = [1, 2, 1, 1, 3, 4, 3, 3, 5]
res = []
for item in a:
    if item not in res:
        res.append(item)
print(res)

[1, 2, 3, 4, 5]


Multiplying all numbers in a list

In [4]:
a = [2, 4, 8, 3]
res = 1
for val in a:
    res = res * val
print(res)

192


Using math.prod()

In [6]:
import math
a = [2, 4, 6, 8]
res = math.prod(a)
print(res)

384


Using reduce and mul

In [7]:
from functools import reduce
from operator import mul

a = [2, 4, 8, 3]
res = reduce(mul, a)
print(res)

192


Using Itertools


In [1]:
from itertools import chain
import time
import numpy as np

def transpose2(M):
    M = M.tolist()
    n = len(M[0])
    L = list((chain(*M)))
    return [L[i::n] for i in range(n)]

m = np.array([[1,2,3], [4,5,6]])
start = time.time_ns()
res = transpose2(m)
end = time.time_ns()

print(res)
print("Time taken", end-start, "ns")

[[1, 4], [2, 5], [3, 6]]
Time taken 0 ns


Using ZIP


In [2]:
m = [(1,2,3), (4,5,6), (7,8,9), (10,11,12)]
t_m = zip(*m)
for row in t_m:
    print(row)

(1, 4, 7, 10)
(2, 5, 8, 11)
(3, 6, 9, 12)


Simple transpose

In [5]:
import numpy as np
m = [(1, 2, 3), (4, 5, 6)]
print(np.transpose(m))

[[1 4]
 [2 5]
 [3 6]]


Using T after the variables

In [7]:
import numpy as np

m = np.array([[1,2,3], [4,5,6]])
print(m.T)

[[1 4]
 [2 5]
 [3 6]]


Multiplication of  two matrix in python

In [8]:
matrix1 = ([[1,2,3], [3,4,5], [7,6,4]])
matrix2 = ([[5,2,6], [5,6,7], [7,6,4]])

res = [[0 for x in range(3)] for y in range(3)]

# Explict for loops
for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range((len(matrix2))):

            # Resulted matrix
            res[i][j] += matrix1[i][j] * matrix2[k][j]
print(res)

[[17, 28, 51], [51, 56, 85], [119, 84, 68]]


Dot products

In [9]:
mat1 = ([1, 6, 5], [3, 4, 8], [2, 12, 3])
mat2 = ([3, 4, 6], [5, 6, 7], [6, 56, 7])

# This will return dot products
res = np.dot(mat1, mat2)
print(res)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


Checkerboard pattern

In [11]:
# Function to print checkerboard pattern

def printcheckerboard(n):
    print("Checkerboard pattern")

    # Create a n * n matrix
    x = np.zeros((n, n), dtype=int)

    # fill with 1 the alternative cells in rows and columns
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1

    # Print the pattern
    for i in range(n):
        for j in range(n):
            print(x[i][j], end="")
        print()

# driver code
n = 8
printcheckerboard(n)

Checkerboard pattern
01010101
10101010
01010101
10101010
01010101
10101010
01010101
10101010


Python program to print nXn Assuming that n

is always even as a checkerboard was

In [20]:
import numpy as np

def printcheckboard(n):
    final = []
    for i in range(n):
        row = np.tile([0, 1], int(n/2)) if i % 2 == 0 else np.tile([1, 0], int(n/2))
        final.append(row)
    print(np.array(final))

# driver code
n = 8
printcheckboard(n)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Matrix Operations


In [24]:
import numpy

# initializating matrics
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# Using add() to add matrics
print("The element wise addition of matrix is:")
print(numpy.add(x, y))

# Using subtract() to substract matrices
print("The element after the substraction is:")
print(numpy.subtract(x, y))

# Using divide() to divide matrics
print("The element wise division of matrix is: ")
print(numpy.divide(x, y))

The element wise addition of matrix is:
[[ 8 10]
 [13 15]]
The element after the substraction is:
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is: 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [26]:
# initializing matrics
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]]) 

# Using multiply() to multiply matrics element wise
print("The element wise multiplication of matrix is :")
print(numpy.multiply(x,y))

# Using dot() to multiply matrices
print("The prduct of matrics is:")
print(numpy.dot(x,y))

The element wise multiplication of matrix is :
[[ 7 16]
 [36 50]]
The prduct of matrics is:
[[25 28]
 [73 82]]
