In [1]:
import numpy as np

In [2]:
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])

Printing a range of Arrays

with the use of slicing method


In [3]:
arr2 = arr[::2, ::2]
print(arr2)

[[-1.   0. ]
 [ 2.6  7. ]]


Data types


Integer Datatype

In [4]:
arr = np.array([1,2])
print(arr.dtype)

int64


Float datatype


In [6]:
x = np.array([1.0, 2.0])
print(x.dtype)


float64


Forced Datatype

In [7]:
x = np.array([1,2], dtype = np.int64)
print(x.dtype)

int64


In [8]:
# first array
arr1 = np.array([[4,7], [2,6]], dtype=np.float64)

# Second array
arr2 = np.array([[3,6], [2,8]], dtype=np.float64)

array addition

In [10]:
Sum = np.add(arr1, arr2)
print(Sum)

[[ 7. 13.]
 [ 4. 14.]]


Addition of all array elements

In [11]:
Sum1 = np.sum(arr1)
print(Sum1)

19.0


Square root of Array

In [12]:
Sqrt = np.sqrt(arr1)
print(Sqrt)

[[2.         2.64575131]
 [1.41421356 2.44948974]]


Transpose of Array

In [13]:
Trans_arr = arr1.T
print(Trans_arr)

[[4. 2.]
 [7. 6.]]


hypot method

In [14]:
leg1 = [12, 3, 4, 6]
print("Leg1 array : ", leg1)

leg2 = [5, 4, 3, 8]
print("leg2 array : ", leg2 )

result = np.hypot(leg1, leg2)
print(result)

Leg1 array :  [12, 3, 4, 6]
leg2 array :  [5, 4, 3, 8]
[13.  5.  5. 10.]
